//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VnManager.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VnManager.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category to.
        /// </summary>
        public static string AddCategoryTo {
            get {
                return ResourceManager.GetString("AddCategoryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Games for Collection.
        /// </summary>
        public static string AddGameCollectionTitle {
            get {
                return ResourceManager.GetString("AddGameCollectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple executables associated with a single ID.
        /// </summary>
        public static string AddGameCollectionTooltip {
            get {
                return ResourceManager.GetString("AddGameCollectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the required information to add a visual novel to this program.
        /// </summary>
        public static string AddGameFillInInfo {
            get {
                return ResourceManager.GetString("AddGameFillInInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This executable has multiple game IDs associated with it.
        /// </summary>
        public static string AddGameLauncherTooltip {
            get {
                return ResourceManager.GetString("AddGameLauncherTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single executable associated with a single ID.
        /// </summary>
        public static string AddGameNormalTooltip {
            get {
                return ResourceManager.GetString("AddGameNormalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Categories.
        /// </summary>
        public static string AddRemoveCategories {
            get {
                return ResourceManager.GetString("AddRemoveCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string AgeColon {
            get {
                return ResourceManager.GetString("AgeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases:.
        /// </summary>
        public static string AliasesColon {
            get {
                return ResourceManager.GetString("AliasesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit.
        /// </summary>
        public static string AppExit {
            get {
                return ResourceManager.GetString("AppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VnManager.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        public static string ArgsColon {
            get {
                return ResourceManager.GetString("ArgsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to import previously saved data?.
        /// </summary>
        public static string AskImportDb {
            get {
                return ResourceManager.GetString("AskImportDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        public static string BirthdayColon {
            get {
                return ResourceManager.GetString("BirthdayColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BloodType:.
        /// </summary>
        public static string BloodTypeColon {
            get {
                return ResourceManager.GetString("BloodTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Database Dump.
        /// </summary>
        public static string BrowseDbDump {
            get {
                return ResourceManager.GetString("BrowseDbDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Exe.
        /// </summary>
        public static string BrowseExe {
            get {
                return ResourceManager.GetString("BrowseExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Cover Image.
        /// </summary>
        public static string BrowseForCover {
            get {
                return ResourceManager.GetString("BrowseForCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Game.
        /// </summary>
        public static string BrowseForGame {
            get {
                return ResourceManager.GetString("BrowseForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Game Icon.
        /// </summary>
        public static string BrowseForIcon {
            get {
                return ResourceManager.GetString("BrowseForIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Icon.
        /// </summary>
        public static string BrowseIcon {
            get {
                return ResourceManager.GetString("BrowseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust-Waist-Hips:.
        /// </summary>
        public static string BustWaistHips {
            get {
                return ResourceManager.GetString("BustWaistHips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Import.
        /// </summary>
        public static string CancelImport {
            get {
                return ResourceManager.GetString("CancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now close this window.
        /// </summary>
        public static string CanCloseWindow {
            get {
                return ResourceManager.GetString("CanCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game must be closed in order to proceed with this operation.
        /// </summary>
        public static string ClosingDisabledGameMessage {
            get {
                return ResourceManager.GetString("ClosingDisabledGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game must be closed.
        /// </summary>
        public static string ClosingDisabledGameTitle {
            get {
                return ResourceManager.GetString("ClosingDisabledGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing is currently disabled.
        /// </summary>
        public static string ClosingDisabledMessage {
            get {
                return ResourceManager.GetString("ClosingDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing is disabled.
        /// </summary>
        public static string ClosingDisabledTitle {
            get {
                return ResourceManager.GetString("ClosingDisabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category?.
        /// </summary>
        public static string ConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Category across all games?.
        /// </summary>
        public static string ConfirmDeleteCategoryMsg {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Image:.
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string CreateCategory {
            get {
                return ResourceManager.GetString("CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Category.
        /// </summary>
        public static string CreatedCategory {
            get {
                return ResourceManager.GetString("CreatedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Global Category.
        /// </summary>
        public static string CreateGlobalCategory {
            get {
                return ResourceManager.GetString("CreateGlobalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a password.
        /// </summary>
        public static string CreatePassTitle {
            get {
                return ResourceManager.GetString("CreatePassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Dump.
        /// </summary>
        public static string DbDump {
            get {
                return ResourceManager.GetString("DbDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error.
        /// </summary>
        public static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is locked by another process.
        /// </summary>
        public static string DbIsLockedProc {
            get {
                return ResourceManager.GetString("DbIsLockedProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is OK.
        /// </summary>
        public static string DbOk {
            get {
                return ResourceManager.GetString("DbOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS PAGE SHOULD ONLY BE ABLE TO BE ACCESSED IF YOU ARE DEBUGGING THE PROGRAM FROM VISUAL STUDIO.
        /// </summary>
        public static string DebugPageWarning1 {
            get {
                return ResourceManager.GetString("DebugPageWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF YOU ARE SEEING THIS PAGE, AND YOU ARE NOT USING VISUAL STUDIO TO DEBUG, DO NOT CLICK ON ANY BUTTON.
        /// </summary>
        public static string DebugPageWarning2 {
            get {
                return ResourceManager.GetString("DebugPageWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF YOU ARE NOT DEBUGGING, CREATE A TICKET ON GITHUB STATING: &quot;Able to access Debug page while in Release&quot;.
        /// </summary>
        public static string DebugPageWarning3 {
            get {
                return ResourceManager.GetString("DebugPageWarning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ALL user data?.
        /// </summary>
        public static string DeleteEverythingTitle {
            get {
                return ResourceManager.GetString("DeleteEverythingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS WILL DELETE ALL USER DATA! ARE YOU SURE YOU WANT TO CONTINUE?.
        /// </summary>
        public static string DeleteEverythingWarning {
            get {
                return ResourceManager.GetString("DeleteEverythingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Game.
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this game?.
        /// </summary>
        public static string DeleteGameCheck {
            get {
                return ResourceManager.GetString("DeleteGameCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a Global Category.
        /// </summary>
        public static string DeleteGlobalCategory {
            get {
                return ResourceManager.GetString("DeleteGlobalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading characters information.
        /// </summary>
        public static string DownCharacterInfo {
            get {
                return ResourceManager.GetString("DownCharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Character Images.
        /// </summary>
        public static string DownCharImages {
            get {
                return ResourceManager.GetString("DownCharImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Cover Image.
        /// </summary>
        public static string DownCoverImage {
            get {
                return ResourceManager.GetString("DownCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Screenshots.
        /// </summary>
        public static string DownScreenshots {
            get {
                return ResourceManager.GetString("DownScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading tag dump.
        /// </summary>
        public static string DownTagDump {
            get {
                return ResourceManager.GetString("DownTagDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading trait dump.
        /// </summary>
        public static string DownTraitDump {
            get {
                return ResourceManager.GetString("DownTraitDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading visual novel information.
        /// </summary>
        public static string DownVnInfo {
            get {
                return ResourceManager.GetString("DownVnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Arguments.
        /// </summary>
        public static string EnableCustomArgs {
            get {
                return ResourceManager.GetString("EnableCustomArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Icon.
        /// </summary>
        public static string EnableCustomIcon {
            get {
                return ResourceManager.GetString("EnableCustomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string EnterPass {
            get {
                return ResourceManager.GetString("EnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Exe already exists in the database.
        /// </summary>
        public static string ExeAlreadyExistsInDb {
            get {
                return ResourceManager.GetString("ExeAlreadyExistsInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exe Path.
        /// </summary>
        public static string ExePath {
            get {
                return ResourceManager.GetString("ExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExeType.
        /// </summary>
        public static string ExeType {
            get {
                return ResourceManager.GetString("ExeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExeType:.
        /// </summary>
        public static string ExeTypeColon {
            get {
                return ResourceManager.GetString("ExeTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be changed once it has been set!.
        /// </summary>
        public static string FirstSetupPassNoChange {
            get {
                return ResourceManager.GetString("FirstSetupPassNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to require a password to use this application?.
        /// </summary>
        public static string FirstSetupRequirePass {
            get {
                return ResourceManager.GetString("FirstSetupRequirePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Id.
        /// </summary>
        public static string GameId {
            get {
                return ResourceManager.GetString("GameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Updated.
        /// </summary>
        public static string GameUpdated {
            get {
                return ResourceManager.GetString("GameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game has been updated.
        /// </summary>
        public static string GameUpdatedMsg {
            get {
                return ResourceManager.GetString("GameUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightColon {
            get {
                return ResourceManager.GetString("HeightColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        public static string IconColon {
            get {
                return ResourceManager.GetString("IconColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Path.
        /// </summary>
        public static string IconPath {
            get {
                return ResourceManager.GetString("IconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import was completed.
        /// </summary>
        public static string ImportComplete {
            get {
                return ResourceManager.GetString("ImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import User Data.
        /// </summary>
        public static string ImportDataTitle {
            get {
                return ResourceManager.GetString("ImportDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Into Database.
        /// </summary>
        public static string ImportIntoDb {
            get {
                return ResourceManager.GetString("ImportIntoDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is invalid/corrupted..
        /// </summary>
        public static string ImportInvalidDb {
            get {
                return ResourceManager.GetString("ImportInvalidDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database.
        /// </summary>
        public static string ImportInvalidDbTitle {
            get {
                return ResourceManager.GetString("ImportInvalidDbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Played.
        /// </summary>
        public static string LastPlayed {
            get {
                return ResourceManager.GetString("LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string Launcher {
            get {
                return ResourceManager.GetString("Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string LengthColon {
            get {
                return ResourceManager.GetString("LengthColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1 Minute.
        /// </summary>
        public static string Less1Min {
            get {
                return ResourceManager.GetString("Less1Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Executables.
        /// </summary>
        public static string ManageExecutables {
            get {
                return ResourceManager.GetString("ManageExecutables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Sexual Level.
        /// </summary>
        public static string MaxSexualLevel {
            get {
                return ResourceManager.GetString("MaxSexualLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Violence Level.
        /// </summary>
        public static string MaxViolenceLevel {
            get {
                return ResourceManager.GetString("MaxViolenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        public static string Minor {
            get {
                return ResourceManager.GetString("Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any games. Please add some games to the database.
        /// </summary>
        public static string NoGamesFound {
            get {
                return ResourceManager.GetString("NoGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repair is available.
        /// </summary>
        public static string NoRepairAvail {
            get {
                return ResourceManager.GetString("NoRepairAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Source.
        /// </summary>
        public static string NoSource {
            get {
                return ResourceManager.GetString("NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Incorrect.
        /// </summary>
        public static string PassIncorrect {
            get {
                return ResourceManager.GetString("PassIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string PasswordNoEmpty {
            get {
                return ResourceManager.GetString("PasswordNoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsNoMatch {
            get {
                return ResourceManager.GetString("PasswordsNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string PathColon {
            get {
                return ResourceManager.GetString("PathColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayTime.
        /// </summary>
        public static string PlayTime {
            get {
                return ResourceManager.GetString("PlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity:.
        /// </summary>
        public static string PopularityColon {
            get {
                return ResourceManager.GetString("PopularityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string RatingColon {
            get {
                return ResourceManager.GetString("RatingColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations.
        /// </summary>
        public static string Relations {
            get {
                return ResourceManager.GetString("Relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released Date:.
        /// </summary>
        public static string ReleasedDateColon {
            get {
                return ResourceManager.GetString("ReleasedDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category.
        /// </summary>
        public static string RemoveCategory {
            get {
                return ResourceManager.GetString("RemoveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category from.
        /// </summary>
        public static string RemoveCategoryFrom {
            get {
                return ResourceManager.GetString("RemoveCategoryFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair/Update Game Data.
        /// </summary>
        public static string RepairGameData {
            get {
                return ResourceManager.GetString("RepairGameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will download a fresh copy of the data, and clearing out any previous entries..
        /// </summary>
        public static string RepairMessage1 {
            get {
                return ResourceManager.GetString("RepairMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to contine with this Repair/Update?.
        /// </summary>
        public static string RepairMessage2 {
            get {
                return ResourceManager.GetString("RepairMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair/Update.
        /// </summary>
        public static string RepairUpdate {
            get {
                return ResourceManager.GetString("RepairUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair/Update Vndb Data.
        /// </summary>
        public static string RepairVndb {
            get {
                return ResourceManager.GetString("RepairVndb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Application.
        /// </summary>
        public static string ResetApplication {
            get {
                return ResourceManager.GetString("ResetApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you SURE you want to reset the entire Application?.
        /// </summary>
        public static string ResetAppWarning {
            get {
                return ResourceManager.GetString("ResetAppWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Nsfw Images in Database.
        /// </summary>
        public static string SaveNsfwImagesInDatabase {
            get {
                return ResourceManager.GetString("SaveNsfwImagesInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        public static string Screenshots {
            get {
                return ResourceManager.GetString("Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Category.
        /// </summary>
        public static string SearchCategory {
            get {
                return ResourceManager.GetString("SearchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Character.
        /// </summary>
        public static string SearchCharacter {
            get {
                return ResourceManager.GetString("SearchCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme:.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get Vndb ID from selected name.
        /// </summary>
        public static string SetIdFromNameFail {
            get {
                return ResourceManager.GetString("SetIdFromNameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been saved.
        /// </summary>
        public static string SettingsSavedMessage {
            get {
                return ResourceManager.GetString("SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved.
        /// </summary>
        public static string SettingsSavedTitle {
            get {
                return ResourceManager.GetString("SettingsSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Type.
        /// </summary>
        public static string SourceType {
            get {
                return ResourceManager.GetString("SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleColon {
            get {
                return ResourceManager.GetString("TitleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        public static string Traits {
            get {
                return ResourceManager.GetString("Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unkown exception has occured.
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password to unlock the database.
        /// </summary>
        public static string UnlockDbTitle {
            get {
                return ResourceManager.GetString("UnlockDbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Paths.
        /// </summary>
        public static string UpdatePaths {
            get {
                return ResourceManager.GetString("UpdatePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data exported to:.
        /// </summary>
        public static string UserDataExportedPath {
            get {
                return ResourceManager.GetString("UserDataExportedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data exported.
        /// </summary>
        public static string UserDataExportedTitle {
            get {
                return ResourceManager.GetString("UserDataExportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userdata has been imported into the database..
        /// </summary>
        public static string UserDataImported {
            get {
                return ResourceManager.GetString("UserDataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Setting config is invalid..
        /// </summary>
        public static string UserSettingsInvalid {
            get {
                return ResourceManager.GetString("UserSettingsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add Category because the max categories has been reached.
        /// </summary>
        public static string ValidationAboveMaxCategories {
            get {
                return ResourceManager.GetString("ValidationAboveMaxCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric characters or spaces are allowed.
        /// </summary>
        public static string ValidationAlphanumericSpace {
            get {
                return ResourceManager.GetString("ValidationAlphanumericSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments cannot be empty.
        /// </summary>
        public static string ValidationArgumentsEmpty {
            get {
                return ResourceManager.GetString("ValidationArgumentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal characters detected.
        /// </summary>
        public static string ValidationArgumentsIllegalChars {
            get {
                return ResourceManager.GetString("ValidationArgumentsIllegalChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid Exe Type.
        /// </summary>
        public static string ValidationBadExeType {
            get {
                return ResourceManager.GetString("ValidationBadExeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid Game ID.
        /// </summary>
        public static string ValidationBadGameID {
            get {
                return ResourceManager.GetString("ValidationBadGameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid ID.
        /// </summary>
        public static string ValidationBadId {
            get {
                return ResourceManager.GetString("ValidationBadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Played time is not valid.
        /// </summary>
        public static string ValidationBadLastPlayed {
            get {
                return ResourceManager.GetString("ValidationBadLastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Time is not valid.
        /// </summary>
        public static string ValidationBadPlayTime {
            get {
                return ResourceManager.GetString("ValidationBadPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid Source Type.
        /// </summary>
        public static string ValidationBadSourceType {
            get {
                return ResourceManager.GetString("ValidationBadSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category already exists.
        /// </summary>
        public static string ValidationCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid Executable.
        /// </summary>
        public static string ValidationExeNotValid {
            get {
                return ResourceManager.GetString("ValidationExeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exe Path cannot be empty.
        /// </summary>
        public static string ValidationExePathEmpty {
            get {
                return ResourceManager.GetString("ValidationExePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid path to exe.
        /// </summary>
        public static string ValidationExePathNotValid {
            get {
                return ResourceManager.GetString("ValidationExePathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed.
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed. Please fix any errors and try again.
        /// </summary>
        public static string ValidationFailedRecheck {
            get {
                return ResourceManager.GetString("ValidationFailedRecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Path cannot be empty.
        /// </summary>
        public static string ValidationIconPathEmpty {
            get {
                return ResourceManager.GetString("ValidationIconPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid path to icon.
        /// </summary>
        public static string ValidationIconPathNotValid {
            get {
                return ResourceManager.GetString("ValidationIconPathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID already exists in the database.
        /// </summary>
        public static string ValidationIdAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid path to an image.
        /// </summary>
        public static string ValidationImagePathNotValid {
            get {
                return ResourceManager.GetString("ValidationImagePathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid image file.
        /// </summary>
        public static string ValidationNotValidImage {
            get {
                return ResourceManager.GetString("ValidationNotValidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID entered is above maximum Vndb ID.
        /// </summary>
        public static string ValidationVnIdAboveMax {
            get {
                return ResourceManager.GetString("ValidationVnIdAboveMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vndb ID entered has been removed or does not exist.
        /// </summary>
        public static string ValidationVnIdDoesNotExist {
            get {
                return ResourceManager.GetString("ValidationVnIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vndb ID must be greater than 0.
        /// </summary>
        public static string ValidationVnIdNotAboveZero {
            get {
                return ResourceManager.GetString("ValidationVnIdNotAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vn Name cannot be empty.
        /// </summary>
        public static string ValidationVnNameEmpty {
            get {
                return ResourceManager.GetString("ValidationVnNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A selection from the list of VN names is required.
        /// </summary>
        public static string ValidationVnNameSelection {
            get {
                return ResourceManager.GetString("ValidationVnNameSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vndb.
        /// </summary>
        public static string Vndb {
            get {
                return ResourceManager.GetString("Vndb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vndb Id or Name:.
        /// </summary>
        public static string VndbIdOrName {
            get {
                return ResourceManager.GetString("VndbIdOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VnDb Spoiler Level.
        /// </summary>
        public static string VndbSpoilerLevel {
            get {
                return ResourceManager.GetString("VndbSpoilerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vn Id:.
        /// </summary>
        public static string VnId {
            get {
                return ResourceManager.GetString("VnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Vndb ID already exists in the database.
        /// </summary>
        public static string VnIdAlreadyExistsInDb {
            get {
                return ResourceManager.GetString("VnIdAlreadyExistsInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vn Name:.
        /// </summary>
        public static string VnName {
            get {
                return ResourceManager.GetString("VnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string WeightColon {
            get {
                return ResourceManager.GetString("WeightColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to Database.
        /// </summary>
        public static string WritingToDb {
            get {
                return ResourceManager.GetString("WritingToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
